# -*- coding: utf-8 -*-
"""nlpdeploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csOmrUNleKFJjjPjgEH5MbkpAwEMwwTE
"""

import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack

# Load Pretrained Components
tfidf = joblib.load("tfidf_vectorizer.pkl")
scaler = joblib.load("scaler.pkl")

log_model = joblib.load("logistic_model.pkl")
svm_model = joblib.load("svm_model.pkl")
nb_model = joblib.load("nb_model.pkl")

models = {
    "Logistic Regression": log_model,
    "Linear SVM": svm_model,
    "Naive Bayes": nb_model
}

# ---------------------
# TEXT CLEANING FUNCTION
# ---------------------
stop_words = set(stopwords.words("english"))

def clean_text(text):
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = text.lower()
    text = ' '.join([w for w in text.split() if w not in stop_words])
    return text

# ---------------------
# PREDICTION FUNCTION
# ---------------------
def predict_sentiment(text, model):
    clean = clean_text(text)

    # TFIDF
    tfidf_features = tfidf.transform([clean])

    # Numeric features
    char_count = len(text)
    word_count = len(text.split())

    numeric_scaled = scaler.transform([[char_count, word_count]])

    # Combine TFIDF + scaled features
    final_features = hstack((tfidf_features, numeric_scaled))

    prediction = model.predict(final_features)[0]
    return prediction

# ---------------------
# STREAMLIT UI
# ---------------------
st.title("📌 Sentiment Analysis Model Deployment")
st.write("Enter a text below and choose a model to get sentiment prediction.")

text_input = st.text_area("Enter your review/comment:")

model_choice = st.selectbox(
    "Choose a model:",
    ("Linear SVM", "Logistic Regression", "Naive Bayes")
)

if st.button("Predict"):
    if text_input.strip() == "":
        st.warning("Please enter some text for prediction.")
    else:
        selected_model = models[model_choice]
        sentiment = predict_sentiment(text_input, selected_model)

        # Color-coded output
        if sentiment == "positive":
            st.success(f"Prediction: {sentiment.upper()} 😊")
        elif sentiment == "negative":
            st.error(f"Prediction: {sentiment.upper()} 😡")
        else:
            st.info(f"Prediction: {sentiment.upper()} 😐")